[input]
description = "deeply nested list with all data types"
is_compressed = false

[input.source]
json_string = '''
{
    "x": {
        "y": {
            "a": [
                {
                    "x": [
                        [
                            {
                                "b": {
                                    "c": 42
                                }
                            },
                            {
                                "b": [
                                    1,
                                    2,
                                    {},
                                    [],
                                    [
                                        []
                                    ],
                                    "xyz",
                                    true,
                                    false,
                                    null
                                ]
                            }
                        ]
                    ]
                },
                {
                    "b": [
                        42
                    ]
                }
            ]
        }
    }
}
'''

[[queries]]
query = "$..a.*..b.*"
description = "select all nodes in bs with mixed segments"

[queries.results]
count = 11
spans = [
    [
        228,
        230,
    ],
    [
        401,
        402,
    ],
    [
        440,
        441,
    ],
    [
        479,
        481,
    ],
    [
        519,
        521,
    ],
    [
        559,
        641,
    ],
    [
        679,
        684,
    ],
    [
        722,
        726,
    ],
    [
        764,
        769,
    ],
    [
        807,
        811,
    ],
    [
        1012,
        1014,
    ],
]
nodes = [
    "42",
    "1",
    "2",
    "{}",
    "[]",
    '''[
                                        []
                                    ]''',
    '"xyz"',
    "true",
    "false",
    "null",
    "42",
]

[[queries]]
query = "$..a..*..b..*"
description = "select all nodes in bs with descendant segments"

[queries.results]
count = 12
spans = [
    [
        228,
        230,
    ],
    [
        401,
        402,
    ],
    [
        440,
        441,
    ],
    [
        479,
        481,
    ],
    [
        519,
        521,
    ],
    [
        559,
        641,
    ],
    [
        601,
        603
    ],
    [
        679,
        684,
    ],
    [
        722,
        726,
    ],
    [
        764,
        769,
    ],
    [
        807,
        811,
    ],
    [
        1012,
        1014,
    ],
]
nodes = [
    "42",
    "1",
    "2",
    "{}",
    "[]",
    '''[
                                        []
                                    ]''',
    "[]",
    '"xyz"',
    "true",
    "false",
    "null",
    "42",
]
