[input]
description = "dense integer atomic leaves without lists"
is_compressed = false

[input.source]
json_string = '''
{
    "x": {
        "y": {
            "a": {
                "b": 42,
                "c": 43,
                "d": 44,
                "e": {
                    "x": 45
                },
                "a": {
                    "a": 46,
                    "x": 47
                }
            }
        }
    }
}
'''

[[queries]]
query = "$..a.*"
description = "descendant search for 'a' and then take all children"

[queries.results]
count = 7
spans = [[68, 70], [93, 95], [118, 120], [143, 190], [213, 289], [240, 242], [269, 271]]
nodes = ["42", "43", "44", '''{
                    "x": 45
                }''', '''{
                    "a": 46,
                    "x": 47
                }''', "46", "47"]

[[queries]]
query = "$..a..*"
description = "descendant search for 'a' and then all subdocuments"

[queries.results]
count = 8
spans = [[68, 70], [93, 95], [118, 120], [143, 190], [170, 172], [213, 289], [240, 242], [269, 271]]
nodes = ["42", "43", "44", '''{
                    "x": 45
                }''', "45", '''{
                    "a": 46,
                    "x": 47
                }''', "46", "47"]

