[input]
description = "empty document"
is_compressed = false

[input.source]
json_string = ""

[[queries]]
query = "$"
description = "select the root"

[queries.results]
count = 0
spans = []
nodes = []