[input]
description = "empty object root"
is_compressed = false

[input.source]
json_string = """
{}
"""

[[queries]]
query = "$"
description = "select the root"

[queries.results]
count = 1
spans = [[0, 2]]
nodes = ["{}"]

[[queries]]
query = "$.a"
description = "select the child named 'a' (which does not exist)"

[queries.results]
count = 0
spans = []
nodes = []

[[queries]]
query = "$.*"
description = "select any child (there are none)"

[queries.results]
count = 0
spans = []
nodes = []

[[queries]]
query = "$..*"
description = "select any descendant (there are none)"

[queries.results]
count = 0
spans = []
nodes = []
