[input]
description = "list with mixed atomic integers and objects"
is_compressed = false

[input.source]
json_string = '''
{
  "a": [
    42,
    {
      "b": 43
    },
    44
  ]
}
'''

[[queries]]
query = "$.a.*"
description = "select all elements on the list"

[queries.results]
count = 3
spans = [[15, 17], [23, 44], [50, 52]]
nodes = ["42", '''{
      "b": 43
    }''', "44"]
