[input]
description = "whitespace separators between structurals to test correctness of index result handling"
is_compressed = false

[input.source]
json_string = """
{"a"  :  [0  ,  1  ,  2]}
"""

[[queries]]
description = "select root"
query = "$"

[queries.results]
count = 1
spans = [[0, 25]]
nodes = ['{"a"  :  [0  ,  1  ,  2]}']

[[queries]]
description = "select a by child"
query = "$.a"

[queries.results]
count = 1
spans = [[9, 24]]
nodes = ["[0  ,  1  ,  2]"]

[[queries]]
description = "select a by descendant"
query = "$..a"

[queries.results]
count = 1
spans = [[9, 24]]
nodes = ["[0  ,  1  ,  2]"]

[[queries]]
description = "select each item on the list with wildcard"
query = "$.a[*]"

[queries.results]
count = 3
spans = [[10, 11], [16, 17], [22, 23]]
nodes = ["0", "1", "2"]
