[input]
description = "deeply nested lists"
is_compressed = false

[input.source]
json_string = '''
{
    "x": {
        "y": {
            "a": [
                1,
                2,
                {},
                [],
                [
                    [
                        [
                            []
                        ]
                    ]
                ],
                3
            ]
        }
    }
}
'''

[[queries]]
query = "$..a.*"
description = "select all nodes in the top-level list"

[queries.results]
count = 6
spans = [[63, 64], [82, 83], [101, 103], [121, 123], [141, 287], [305, 306]]
nodes = ["1", "2", "{}", "[]", '''[
                    [
                        [
                            []
                        ]
                    ]
                ]''', "3"]

[[queries]]
query = "$..a..*"
description = "select all nodes in the top-level list and below"

[queries.results]
count = 9
spans = [
    [
        63,
        64,
    ],
    [
        82,
        83,
    ],
    [
        101,
        103,
    ],
    [
        121,
        123,
    ],
    [
        141,
        287,
    ],
    [
        163,
        269,
    ],
    [
        189,
        247,
    ],
    [
        219,
        221,
    ],
    [
        305,
        306,
    ],
]
nodes = ["1", "2", "{}", "[]", '''[
                    [
                        [
                            []
                        ]
                    ]
                ]''', '''[
                        [
                            []
                        ]
                    ]''', '''[
                            []
                        ]''', "[]", "3"]
