# Define the JSON input for all query test cases.
[input]
# Short description of the input structure.
description = "List with nested sublists to stress output ordering."
 # Set to true only if your specific test input is fully compressed (no extraneous whitespace).
is_compressed = false

# Inline JSON document.
[input.source]
json_string = '''
[
  1,
  2,
  [
    {},
    4
  ],
  [
    5
  ]
]
'''

# Define queries to test on the input.
[[queries]]
 # Valid JSONPath query string.
query = "$..*"
# Short descritpion of the query semantics.
description = "select all subdocuments"

[queries.results]
# Number of expected matches.
count = 7
# Byte locations of spans of all matches, in order.
spans = [[4, 5], [9, 10], [14, 33], [20, 22], [28, 29], [37, 48], [43, 44]] 
# Stringified values of all matches, verbatim as in the input,
# in the same order as above.
nodes = [
  "1",
  "2",
  '''[
    {},
    4
  ]''',
  "{}",
  "4",
  '''[
    5
  ]''',
  "5"
]