[input]
description = "extract from twitter json containing urls with multiple escaped slashes"
is_compressed = false

[input.source]
json_string = '''
[
    {
        "user": {
            "url": "http:\/\/www.roadshowrigoletto.com\/"
        },
        "retweeted_status": {
            "user": {
                "url": "http:\/\/www.thinkprogress.org"
            },
            "entities": {
                "urls": [
                    {
                        "url": "https:\/\/t.co\/B6T1jj2hST"
                    }
                ],
                "media": [
                    {
                        "url": "https:\/\/t.co\/blQy8JxViF"
                    }
                ]
            },
            "extended_entities": {
                "media": [
                    {
                        "url": "https:\/\/t.co\/blQy8JxViF"
                    }
                ]
            }
        },
        "entities": {
            "hashtags": [],
            "urls": [
                {
                    "url": "https:\/\/t.co\/B6T1jj2hST"
                }
            ],
            "media": [
                {
                    "url": "https:\/\/t.co\/blQy8JxViF"
                }
            ]
        },
        "url": "https:\/\/t.co\/blQy8JxViF"
    }
]
'''

[[queries]]
query = "$..url"
description = "descendant search for url"

[queries.results]
count = 8
spans = [
    [
        45,
        83,
    ],
    [
        170,
        202,
    ],
    [
        323,
        351,
    ],
    [
        473,
        501,
    ],
    [
        672,
        700,
    ],
    [
        883,
        911,
    ],
    [
        1013,
        1041,
    ],
    [
        1100,
        1128,
    ],
]
nodes = [
    '''"http:\/\/www.roadshowrigoletto.com\/"''',
    '''"http:\/\/www.thinkprogress.org"''',
    '''"https:\/\/t.co\/B6T1jj2hST"''',
    '''"https:\/\/t.co\/blQy8JxViF"''',
    '''"https:\/\/t.co\/blQy8JxViF"''',
    '''"https:\/\/t.co\/B6T1jj2hST"''',
    '''"https:\/\/t.co\/blQy8JxViF"''',
    '''"https:\/\/t.co\/blQy8JxViF"''',
]

[[queries]]
query = "$..entities..url"
description = "descendant entities then url"

[queries.results]
count = 4
spans = [[323, 351], [473, 501], [883, 911], [1013, 1041]]
nodes = [
    '''"https:\/\/t.co\/B6T1jj2hST"''',
    '''"https:\/\/t.co\/blQy8JxViF"''',
    '''"https:\/\/t.co\/B6T1jj2hST"''',
    '''"https:\/\/t.co\/blQy8JxViF"''',
]

[[queries]]
query = "$..entities..urls..url"
description = "descendant for url limited to urls arrays"

[queries.results]
count = 2
spans = [[323, 351], [883, 911]]
nodes = ['''"https:\/\/t.co\/B6T1jj2hST"''', '''"https:\/\/t.co\/B6T1jj2hST"''']

[[queries]]
query = "$..entities.urls..url"
description = "descendant for url limited to direct urls arrays"

[queries.results]
count = 2
spans = [[323, 351], [883, 911]]
nodes = ['''"https:\/\/t.co\/B6T1jj2hST"''', '''"https:\/\/t.co\/B6T1jj2hST"''']

[[queries]]
query = "$[0].url"
description = "direct path to the top-level url"

[queries.results]
count = 1
spans = [[1100, 1128]]
nodes = ['''"https:\/\/t.co\/blQy8JxViF"''']
