[[queries]]
query = "$..user..entities..url"
description = "descendant user entities url"

[queries.results]
count = 44
spans = [
    [
        5465,
        5978,
    ],
    [
        5570,
        5594,
    ],
    [
        9496,
        9520,
    ],
    [
        9985,
        10009,
    ],
    [
        18496,
        19037,
    ],
    [
        18601,
        18625,
    ],
    [
        23338,
        23875,
    ],
    [
        23443,
        23467,
    ],
    [
        24017,
        24041,
    ],
    [
        89785,
        90370,
    ],
    [
        89902,
        89926,
    ],
    [
        112198,
        112753,
    ],
    [
        112315,
        112339,
    ],
    [
        134220,
        134778,
    ],
    [
        134337,
        134361,
    ],
    [
        134936,
        134960,
    ],
    [
        201055,
        201566,
    ],
    [
        201160,
        201184,
    ],
    [
        205281,
        205850,
    ],
    [
        205398,
        205422,
    ],
    [
        206008,
        206030,
    ],
    [
        333130,
        333668,
    ],
    [
        333235,
        333260,
    ],
    [
        352432,
        352954,
    ],
    [
        352537,
        352561,
    ],
    [
        353096,
        353120,
    ],
    [
        357000,
        357571,
    ],
    [
        357117,
        357141,
    ],
    [
        399785,
        400346,
    ],
    [
        399902,
        399926,
    ],
    [
        451854,
        451876,
    ],
    [
        475584,
        476113,
    ],
    [
        475689,
        475713,
    ],
    [
        511442,
        511953,
    ],
    [
        511547,
        511571,
    ],
    [
        516538,
        517047,
    ],
    [
        516643,
        516667,
    ],
    [
        728252,
        728800,
    ],
    [
        728357,
        728381,
    ],
    [
        743602,
        744157,
    ],
    [
        743719,
        743743,
    ],
    [
        762797,
        763332,
    ],
    [
        762902,
        762926,
    ],
    [
        763474,
        763498,
    ],
]

[[queries]]
query = "$..user..entities.url"
description = "descendant user entities, then child url"

[queries.results]
count = 18
spans = [
    [
        5465,
        5978,
    ],
    [
        18496,
        19037,
    ],
    [
        23338,
        23875,
    ],
    [
        89785,
        90370,
    ],
    [
        112198,
        112753,
    ],
    [
        134220,
        134778,
    ],
    [
        201055,
        201566,
    ],
    [
        205281,
        205850,
    ],
    [
        333130,
        333668,
    ],
    [
        352432,
        352954,
    ],
    [
        357000,
        357571,
    ],
    [
        399785,
        400346,
    ],
    [
        475584,
        476113,
    ],
    [
        511442,
        511953,
    ],
    [
        516538,
        517047,
    ],
    [
        728252,
        728800,
    ],
    [
        743602,
        744157,
    ],
    [
        762797,
        763332,
    ],
]

[[queries]]
query = "$.search_metadata.count"
description = "select metadata count directly"

[queries.results]
count = 1
spans = [[767233, 767236]]
nodes = ["100"]

[[queries]]
query = "$..search_metadata.count"
description = "select metadata count by descendant (should use memchr)"

[queries.results]
count = 1
spans = [[767233, 767236]]
nodes = ["100"]

[[queries]]
query = "$.search_metadata..count"
description = "select metadata directly, and then count by descendant"

[queries.results]
count = 1
spans = [[767233, 767236]]
nodes = ["100"]

[[queries]]
query = "$..search_metadata..count"
description = "select metadata and count by descendant (should use memchr)"

[queries.results]
count = 1
spans = [[767233, 767236]]
nodes = ["100"]

[[queries]]
query = "$..count"
description = "select count by descendant (should use memchr)"

[queries.results]
count = 1
spans = [[767233, 767236]]
nodes = ["100"]

[input]
description = "twitter json from simdjson github example"
is_compressed = false

[input.source]
large_file = "large/twitter.json"
