# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
      time: "20:00"
    assignees:
      - V0ldek
    commit-message:
      prefix: "dep:"
    groups:
      dev-deps:
        dependency-type: development
      deps:
        dependency-type: production
        update-types:
          - patch
          - minor

  - package-ecosystem: cargo
    directory: /crates/rsonpath-test-codegen
    schedule:
      interval: daily
      time: "20:01"
    assignees:
      - V0ldek
    commit-message:
      prefix: "chore(dep):"
    groups:
      test-deps:

  - package-ecosystem: cargo
    directory: /crates/rsonpath-test
    schedule:
      interval: daily
      time: "20:01"
    assignees:
      - V0ldek
    commit-message:
      prefix: "chore(dep):"
    groups:
      test-deps:

  - package-ecosystem: cargo
    directory: /fuzz
    schedule:
      interval: daily
      time: "20:01"
    assignees:
      - V0ldek
    commit-message:
      prefix: "chore(dep):"
    groups:
      test-deps:

  - package-ecosystem: docker
    directory: /.clusterfuzzlite
    schedule:
      interval: daily
      time: "20:02"
    assignees:
      - V0ldek
    commit-message:
      prefix: "chore(ci):"
    groups:
      clusterfuzzlite-deps:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "20:02"
    assignees:
      - V0ldek
    commit-message:
      prefix: "chore(ci):"
    groups:
      ci-deps:
