[workspace]

members = [
    "crates/rsonpath",
    "crates/rsonpath-benchmarks",
    "crates/rsonpath-lib"
]

[profile.dev]
lto = false

[profile.release]
lto = "thin"

[patch.crates-io]
rsonpath-lib = { path = "./crates/rsonpath-lib" }