[package]
name = "rsonpath"
version = "0.9.0"
authors = ["Mateusz Gienieczko <mat@gienieczko.com>"]
description = "Blazing fast JSONPath CLI tool powered by SIMD"
readme = "../../README.md"
license = "MIT"
keywords = ["json", "jsonpath", "query", "search", "cli"]
categories = [
    "command-line-utilities",
    "text-processing",
    "parser-implementations",
]
repository = "https://github.com/V0ldek/rsonpath"
homepage = "https://v0ldek.github.io/rsonpath/"
build = "build.rs"
workspace = "../.."
edition = "2021"
rust-version = "1.74.0"

[[bin]]
bench = false
path = "./src/main.rs"
name = "rq"

[dependencies]
clap = { version = "4.5.2", features = ["derive", "wrap_help"] }
color-eyre = { version = "0.6.2", default-features = false }
eyre = "0.6.12"
log = "0.4.21"
rsonpath-lib = { version = "0.9.0", package = "rsonpath-lib", default-features = false }
rsonpath-syntax = { version = "0.3.1", features = ["color"] }
simple_logger = "4.3.3"

[build-dependencies]
rustflags = { version = "0.1.4" }
vergen = { version = "8.3.1", features = ["cargo", "git", "gitcl", "rustc"] }

[dev-dependencies]
trycmd = "0.15.0"

[features]
default = ["simd"]
simd = ["rsonpath-lib/simd"]
