[package]
name = "rsonpath"
version = "0.8.4"
authors = ["Mateusz Gienieczko <mat@gienieczko.com>"]
description = "Blazing fast JSONPath CLI tool powered by SIMD"
readme = "../../README.md"
license = "MIT"
keywords = ["json", "jsonpath", "query", "search", "cli"]
categories = [
    "command-line-utilities",
    "text-processing",
    "parser-implementations",
]
repository = "https://github.com/V0ldek/rsonpath"
homepage = "https://v0ldek.github.io/rsonpath/"
build = "build.rs"
workspace = "../.."
edition = "2021"
rust-version = "1.70"

[[bin]]
bench = false
path = "./src/main.rs"
name = "rq"

[dependencies]
clap = { version = "4.4.8", features = ["derive", "wrap_help"] }
color-eyre = { version = "0.6.2", default-features = false }
eyre = "0.6.8"
log = "0.4.20"
rsonpath-lib = { version = "0.8.4", package = "rsonpath-lib", default-features = false }
rsonpath-syntax = { version = "0.1.0", default-features = false }
simple_logger = "4.2.0"

[build-dependencies]
rustflags = { version = "0.1.4" }
vergen = { version = "8.2.6", features = ["cargo", "git", "gitcl", "rustc"] }

[dev-dependencies]
trycmd = "0.14.19"

[features]
default = ["simd"]
simd = ["rsonpath-lib/simd"]
