[package]
name = "rsonpath"
version = "0.2.1"
authors = ["Mateusz Gienieczko <mat@gienieczko.com>"]
edition = "2021"
description = "Blazing fast JSONPath CLI application powered by SIMD."
readme = "../../README.md"
license = "MIT"
keywords = ["json", "jsonpath", "query", "simd", "cli"]
categories = [
    "command-line-utilities",
    "text-processing",
    "parser-implementations",
]
repository = "https://github.com/V0ldek/rsonpath"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
clap = { version = "4.0.25", features = ["derive", "wrap_help"] }
color-eyre = { version = "0.6.2", default-features = false }
eyre = "0.6.8"
log = "0.4.17"
rsonpath-lib = { version = "0.2.1", default-features = false }
simple_logger = "4.0.0"

[features]
default = ["simd"]
simd = ["rsonpath-lib/simd"]
commas = ["rsonpath-lib/commas"]
