[package]
name = "rsonpath-test-codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.164", features = ["derive"] }
toml = "0.7.4"
proc-macro2 = "1.0.39"
quote = "1.0.18"
heck = { version = "0.4.1", features = ["unicode"] }
walkdir = "2.3.3"

[dev-dependencies]
pretty_assertions = "1.3.0"
