[package]
name = "rsonpath-test-codegen"
version = "0.8.4"
authors = ["Mateusz Gienieczko <mat@gienieczko.com>"]
description = "TOML-based test codegen for rsonpath-lib."
readme = "README.md"
license = "MIT"
keywords = ["json", "jsonpath", "query", "simd", "parser"]
categories = [
    "text-processing",
]
repository = "https://github.com/V0ldek/rsonpath"
edition = "2021"
rust-version = "1.70.0"
publish = false

[dependencies]
serde = { version = "1.0.195", features = ["derive"] }
toml = "0.8.8"
proc-macro2 = "1.0.76"
quote = "1.0.33"
heck = { version = "0.4.1", features = ["unicode"] }
walkdir = "2.4.0"

[dev-dependencies]
pretty_assertions = "1.4.0"
