[package]
name = "rsonpath-test-codegen"
version = "0.5.0"
authors = ["Mateusz Gienieczko <mat@gienieczko.com>"]
edition = "2021"
description = "Blazing fast JSONPath query engine powered by SIMD. TOML-based test codegen for rsonpath-lib."
readme = "README.md"
license = "MIT"
keywords = ["json", "jsonpath", "query", "simd", "parser"]
exclude = ["/tests"]
categories = [
    "text-processing",
]
repository = "https://github.com/V0ldek/rsonpath"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.164", features = ["derive"] }
toml = "0.7.4"
proc-macro2 = "1.0.39"
quote = "1.0.18"
heck = { version = "0.4.1", features = ["unicode"] }
walkdir = "2.3.3"

[dev-dependencies]
pretty_assertions = "1.3.0"
