[package]
name = "rsonpath-lib"
version = "0.2.2"
authors = ["Mateusz Gienieczko <mat@gienieczko.com>"]
edition = "2021"
description = "Blazing fast JSONPath query engine powered by SIMD. Core library of `rsonpath`."
readme = "../../README.md"
license = "MIT"
keywords = ["json", "jsonpath", "query", "simd", "parser"]
exclude = ["/tests", "/proptest-regressions"]
categories = [
    "text-processing",
    "parser-implementations",
]
repository = "https://github.com/V0ldek/rsonpath"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
aligners = "0.0.10"
cfg-if = "1.0.0"
firestorm = "0.5.1"
log = "0.4.17"
memchr = "2.5.0"
nom = "7.1.3"
replace_with = "0.1.7"
smallvec = { version = "1.10.0", features = ["union"] }
thiserror = "1.0.38"
vector-map = "1.0.1"

[dev-dependencies]
itertools = "0.10.5"
pretty_assertions = "1.3.0"
proptest = "1.0.0"
test-case = "2.2.2"

[build-dependencies]
eyre = "0.6.8"

[features]
default = ["simd", "head-skip"]
simd = []
head-skip = []
profiling = ["firestorm/enable_system_time"]
