[package]
name = "rsonpath-lib"
version = "0.6.1"
authors = ["Mateusz Gienieczko <mat@gienieczko.com>"]
edition = "2021"
description = "Blazing fast JSONPath query engine powered by SIMD. Core library of `rsonpath`."
readme = "README.md"
license = "MIT"
keywords = ["json", "jsonpath", "query", "simd", "parser"]
exclude = ["/tests", "/proptest-regressions"]
categories = [
    "text-processing",
    "parser-implementations",
]
repository = "https://github.com/V0ldek/rsonpath"
rust-version = "1.67.1"

[lib]
bench = false
name = "rsonpath"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
cfg-if = "1.0.0"
log = "0.4.19"
memchr = "2.5.0"
memmap2 = "0.7.1"
nom = "7.1.3"
replace_with = "0.1.7"
smallvec = { version = "1.11.0", features = ["union"] }
static_assertions = "1.1.0"
thiserror = "1.0.46"
vector-map = "1.0.1"

[dev-dependencies]
itertools = "0.11.0"
pretty_assertions = "1.4.0"
proptest = "1.2.0"
test-case = "3.1.0"

[features]
default = ["simd"]
simd = []