[package]
name = "rsonpath-lib"
version = "0.8.2"
authors = ["Mateusz Gienieczko <mat@gienieczko.com>"]
edition = "2021"
description = "Blazing fast JSONPath query engine powered by SIMD. Core library of `rsonpath`."
readme = "README.md"
license = "MIT"
keywords = ["json", "jsonpath", "query", "simd", "parser"]
exclude = ["/tests", "/proptest-regressions"]
categories = [
    "text-processing",
    "parser-implementations",
]
repository = "https://github.com/V0ldek/rsonpath"
rust-version = "1.67.1"

[lib]
bench = false
name = "rsonpath"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
features = [ "arbitrary" ]

[dependencies]
arbitrary = { version = "1.3.0", features = ["derive"], optional = true }
cfg-if = "1.0.0"
log = "0.4.20"
memmap2 = "0.9.0"
nom = "7.1.3"
smallvec = { version = "1.11.1", features = ["union"] }
static_assertions = "1.1.0"
thiserror = "1.0.49"
vector-map = "1.0.1"

[dev-dependencies]
itertools = "0.11.0"
pretty_assertions = "1.4.0"
proptest = "1.3.1"
test-case = "3.2.1"

[features]
default = ["simd"]
arbitrary = ["dep:arbitrary"]
simd = []

[[example]]
name = "approx_spans_usage"
path = "examples/approx_spans_usage.rs"
doc-scrape-examples = true