[package]
name = "rsonpath-lib"
version = "0.8.4"
authors = ["Mateusz Gienieczko <mat@gienieczko.com>"]
description = "Blazing fast JSONPath query engine powered by SIMD. Core library of `rsonpath`."
readme = "README.md"
license = "MIT"
keywords = ["json", "jsonpath", "query", "search", "simd"]
exclude = [
    "/tests",
    "/proptest-regressions",
    "/src/classification/classifier_correctness_tests.rs",
    "/src/classification/classifier_correctness_tests.proptest-regressions",
]
categories = ["text-processing"]
repository = "https://github.com/V0ldek/rsonpath"
homepage = "https://v0ldek.github.io/rsonpath/"
edition = "2021"
rust-version = "1.67.1"

[lib]
bench = false
name = "rsonpath"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
all-features = true

[dependencies]
arbitrary = { version = "1.3.1", features = ["derive"], optional = true }
cfg-if = "1.0.0"
log = "0.4.20"
memmap2 = "0.9.3"
nom = "7.1.3"
rsonpath-syntax = { version = "0.1.0", path = "../rsonpath-syntax" }
smallvec = { version = "1.11.2", features = ["union"] }
static_assertions = "1.1.0"
thiserror = "1.0.56"
vector-map = "1.0.1"

[dev-dependencies]
itertools = "0.12.0"
pretty_assertions = "1.4.0"
proptest = "1.4.0"
test-case = "3.3.1"

[features]
default = ["simd"]
arbitrary = ["dep:arbitrary"]
simd = []

[[example]]
name = "approx_spans_usage"
path = "examples/approx_spans_usage.rs"
doc-scrape-examples = true
