[package]
name = "rsonpath-test"
version = "0.8.1"
authors = ["Mateusz Gienieczko <mat@gienieczko.com>"]
edition = "2021"
description = "Just a build script for the auto test generation."
readme = "README.md"
license = "MIT"
keywords = ["json", "jsonpath", "query", "simd", "parser"]
categories = [
    "text-processing",
]
repository = "https://github.com/V0ldek/rsonpath"
rust-version = "1.70.0"
publish = false

[build-dependencies]
eyre = "0.6.8"
md5 = "0.7.0"
rsonpath-test-codegen = { version = "0.8.0", path = "../rsonpath-test-codegen" }