[package]
name = "rsonpath-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
pretty_assertions = "1.3.0"
rayon = "1.7.0"
serde = { version = "1.0.164", features = ["derive"] }
test-case = "3.1.0"
toml = "0.7.4"
md5 = "0.7.0"
proc-macro2 = "1.0.39"
quote = "1.0.18"
heck = { version = "0.4.1", features = ["unicode"] }
