[package]
name = "rsonpath-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.7"
itertools = "0.10.5"
pretty_assertions = "1.3.0"
proptest = "1.2.0"
rayon = "1.7.0"
serde = { version = "1.0.164", features = ["derive"] }
test-case = "3.1.0"
toml = "0.7.4"
rsonpath = { package = "rsonpath-lib", version = "0.5.0", default-features = false }