[package]
name = "rsonpath-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
pretty_assertions = "1.3.0"
rsonpath-lib = { path = "../rsonpath-lib" }
tempfile = "3.6.0"

[build-dependencies]
eyre = "0.6.8"
rsonpath-test-codegen = { path = "../rsonpath-test-codegen" }