[book]
title = "rsonbook"
authors = ["Mateusz Gienieczko <mat@gienieczko.com>"]
description = "User and developer guide for the rsonpath project."
src = "src"
language = "en"
multilingual = false

[rust]
edition = "2021"

[build]
build-dir = "wwwroot"

[preprocessor.katex]
after = ["links"]

[output.html]
preferred-dark-theme = "ayu"
curly-quotes = true
mathjax-support = false # we use katex
additional-css = ["rsonbook.css"]
git-repository-url = "https://github.com/v0ldek/rsonpath"
edit-url-template = "https://github.com/v0ldek/rsonpath/book/{path}"
