name: New Issue
on:
  issues:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
    - name: Output event
      run: "echo '${{ github.event }}'"
    - name: GitHub GraphQL API Query
      id: get-ids
      uses: octokit/graphql-action@v2.2.1
      with:
        query: |
            query GetIds($owner:String!,$repo:String!) {
              repository(owner:$owner,name:$repo) {
                label(name: "acceptance: triage") {
                  id
                }
                issue(number: 53) {
                  id
                  labels(first: 100) {
                    nodes {
                      id
                    }
                  }
                }
              }
            }
        owner: ${{ github.event.repository.owner.login }}
        repo: ${{ github.event.repository.name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Parse data
      id: issue-data
      run: |
        "echo 'labels=${{ toJSON(fromJSON(steps.get-ids.outputs.data).repository.issue.labels.nodes.*.id) }}' >> $GITHUB_OUTPUT"
        "echo 'triage-id=${{ fromJSON(steps.get-ids.outputs.data).repository.issue.label.id) }}' >> $GITHUB_OUTPUT"
        "echo 'issue-id=${{ fromJSON(steps.get-ids.outputs.data).repository.issue.id) }}' >> $GITHUB_OUTPUT"
      
    
