name: "Nix Shell Build"
on:
  pull_request:
    branches: [ "main", "nix" ]
  push:
    branches: [ "main", "nix" ]
    
permissions:
  contents: read

jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          submodules: true
      - uses: cachix/install-nix-action@6ed004b9ccb68dbc28e7c85bee15fa93dbd214ac # v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: rrbutani/use-nix-shell-action@59a52b2b9bbfe3cc0e7deb8f9059abe37a439edf # v1.1.0
        with:
          file: shell.nix
      - name: Build
        run: just build
