name: Release

on:
  workflow_dispatch:
    inputs:
      level:
        description: 'Version bump level'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major 
  push:
    tags:
      - v**

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            triple: aarch64-unknown-linux-gnu
            target-features: ''
            artifact-suffix: 'nosimd'
          - os: ubuntu-latest
            triple: i686-unknown-linux-gnu
            target-features: '+avx2,+pclmulqdq'
            artifact-suffix: 'avx2-pclmulqdq'
          - os: ubuntu-latest
            triple: x86_64-unknown-linux-gnu
            target-features: '+avx2,+pclmulqdq'
            artifact-suffix: 'avx2-pclmulqdq'
          - os: macos-latest
            triple: x86_64-apple-darwin
            target-features: '+avx2,+pclmulqdq'
            artifact-suffix: 'avx2-pclmulqdq'
          - os: windows-latest
            triple: i686-pc-windows-gnu
            target-features: '+avx2,+pclmulqdq'
            artifact-suffix: 'avx2-pclmulqdq'
          - os: windows-latest
            triple: i686-pc-windows-msvc
            target-features: '+avx2,+pclmulqdq'
            artifact-suffix: 'avx2-pclmulqdq'
          - os: windows-latest
            triple: x86_64-pc-windows-gnu
            target-features: '+avx2,+pclmulqdq'
            artifact-suffix: 'avx2-pclmulqdq'
          - os: windows-latest
            triple: x86_64-pc-windows-msvc
            target-features: '+avx2,+pclmulqdq'
            artifact-suffix: 'avx2-pclmulqdq'
    steps:
    - uses: actions/checkout@v3
    - id: metadata
      run: echo 'version=$(git describe --tags --abbrev=0)\n' > $GITHUB_OUTPUT
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        target: ${{ matrix.triple }}
    - name: Cache restore
      id: cache-restore
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ matrix.os }}-${{ matrix.triple }}-${{ matrix.artifact-suffix }}-cargo-${{ hashFiles('**/Cargo.toml') }}-release
    - name: Build release without simd
      if: matrix.target-features == ''
      run: cargo build --package rsonpath --release --no-default-features
      env:
        RUSTFLAGS: "--deny warnings"
    - name: Build release with target-feature=${{ matrix.target-features }}
      if: matrix.target-features != ''
      run: cargo build --package rsonpath --release
      env:
        RUSTFLAGS: "-C target-feature=${{ matrix.target-features }} --deny warnings"
    - name: Upload the binary as artifact
      if: matrix.os != 'windows-latest'
      uses: actions/upload-artifact@v3.1.1
      with:
        name: rsonpath-${{ matrix.triple }}-${{ matrix.artifact-suffix }}-${{ steps.metadata.outputs.version }}
        path: target/release/rsonpath
        if-no-files-found: error    
    - name: Upload the exe as artifact
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v3.1.1
      with:
        name: rsonpath-${{ matrix.triple }}-${{ matrix.artifact-suffix }}-${{ steps.metadata.outputs.version }}
        path: target/release/rsonpath.exe
        if-no-files-found: error
    
  github-release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - id: metadata
      run: echo 'version=$(git describe --tags --abbrev=0)\n' > $GITHUB_OUTPUT
    - name: Download artifacts from build
      uses: actions/download-artifact@v3.0.1
      with:
        path: release/
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: release/*
        fail_on_unmatched_files: true
        generate_release_notes: true
        prerelease: ${{ endsWith(steps.metadata.outputs.version, 'rc') || endsWith(steps.metadata.outputs.version, 'alpha') || endsWith(steps.metadata.outputs.version, 'beta') }}
        draft: true
