name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - nightly
        os: 
          - ubuntu-latest
          - windows-latest
          #- macos-latest
        target_feature:
          - avx2
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: rustup toolchain install
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Cache restore
        id: cache-restore
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.os }}-${{ matrix.rust }}-${{ matrix.target_feature }}-cargo-${{ hashFiles('**/Cargo.toml') }}
      - name: Install cargo-hack
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: cargo install cargo-hack
        env:
          CARGO_TARGET_DIR: target/
      - name: Build all feature sets
        run: cargo install hack build --workspace --exclude rsonpath-benchmarks --feature-powerset --skip default
        env:
          RUSTFLAGS: "-C target-feature=+${{ matrix.target_feature }} --deny warnings"
      - name: Test all feature sets
        run: cargo hack test --workspace --exclude rsonpath-benchmarks --feature-powerset --skip default
        env:
          RUSTFLAGS: "-C target-feature=+${{ matrix.target_feature }} --deny warnings"

  clippy:
    permissions:
      checks: write
    name: Clippy (stable)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true      
    - name: Rustup stable toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: clippy, rustfmt
    - name: Cache restore
      id: cache-restore
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ubuntu-latest-stable-avx2-cargo-${{ hashFiles('**/Cargo.toml') }}-clippy
    - name: Build all features
      run: cargo build --workspace --exclude rsonpath-benchmarks --all-features --release
      env:
        RUSTFLAGS: "-C target-feature=+avx2 --deny warnings"
    - name: Clippy all features
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --workspace --exclude rsonpath-benchmarks --all-features --release -- --deny warnings
      env:
        RUSTFLAGS: "-C target-feature=+avx2"

  clippy-nightly:
    permissions:
      checks: write
    name: Clippy (nightly)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Rustup nightly toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly
        components: clippy, rustfmt
    - name: Cache restore
      id: cache-restore
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ubuntu-latest-nightly-avx2-cargo-${{ hashFiles('**/Cargo.toml') }}-clippy
    - name: Build all features
      run: cargo build --workspace --exclude rsonpath-benchmarks --all-features --release
      env:
        RUSTFLAGS: "-C target-feature=+avx2 --deny warnings"
    - name: Clippy all features
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --workspace --exclude rsonpath-benchmarks --all-features --release -- --deny warnings
      env:
        RUSTFLAGS: "-C target-feature=+avx2"

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Rustup nightly toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy, rustfmt
      - name: Cache restore
        id: cache-restore
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ubuntu-latest-nightly-avx2-cargo-${{ hashFiles('**/Cargo.toml') }}-doc
      - name: cargo doc
        run: cargo doc --package rsonpath-lib --all-features --no-deps
        env:
          RUSTFLAGS: "-C target-feature=+avx2"
          RUSTDOCFLAGS: "-Dwarnings --cfg docsrs"

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Rustup stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Format
        run: cargo fmt --package rsonpath rsonpath-lib -- --check
