name: rsonpath-test codegen

on:
  workflow_call:
    outputs:
      artifact-name:
        description: Name of the produced artifact.
        value: rsonpath-test-documents
      artifact-path:
        description: Path to which the artifact should be extracted.
        value: crates/rsonpath-test

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RSONPATH_ENABLE_TEST_CODEGEN: 1
  CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG: "true"

permissions:
  contents: read

jobs:
  # Run the test codegen build step once and save the artifact to be used for all other steps.
  # This cuts down on CI time, since otherwise we'd regenerate tests on every step of the feature powerset test run.
  test-gen:
    name: Generate rsonpath-test cases
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            azure.archive.ubuntu.com:80
            crates.io:443
            index.crates.io:443
            static.crates.io:443
            static.rust-lang.org:443

      - name: Install lld
        run: sudo apt install lld
      - name: Checkout sources
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: true
      - name: Install Rust toolchain (stable)
        uses: dtolnay/rust-toolchain@1482605bfc5719782e1267fd0c0cc350fe7646b8 # master
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
      - name: Override toolchain
        run: rustup override set stable
      - name: Cache restore (Cargo)
        id: cache-restore-cargo
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: x86_64-unknown-linux-gnu-x86_64-unknown-linux-gnu--cargo-${{ hashFiles('**/Cargo.toml') }}
      - name: Build with test codegen
        id: build-test-codegen
        run: cargo build -p rsonpath-test -vv
      - name: Upload generated tests as artifact
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
        with:
          name: rsonpath-test-documents
          path: |
            crates/rsonpath-test/documents
            crates/rsonpath-test/tests
          retention-days: 1
