name: rsonpath-test codegen

on:
  workflow_call:
    outputs:
      artifact-name:
        description: Name of the produced artifact.
        value: rsonpath-test-documents
      artifact-path:
        description: Path to which the artifact should be extracted.
        value: crates/rsonpath-lib/tests/documents

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RSONPATH_ENABLE_TEST_CODEGEN: 1
  
permissions:
  contents: read

jobs:
  # Run the test codegen build step once and save the artifact to be used for all other steps.
  # This cuts down on CI time, since otherwise we'd regenerate tests on every step of the feature powerset test run.
  test-gen:
    name: Generate rsonpath-test cases
    runs-on: ubuntu-latest
    steps:
      - name: Install lld
        run: sudo apt install lld
      - name: Checkout sources
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          submodules: true
      - name: Install Rust toolchain (stable)
        uses: dtolnay/rust-toolchain@f361669954a8ecfc00a3443f35f9ac8e610ffc06 # master
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
      - name: Override toolchain
        run: rustup override set stable
      - name: Cache restore (Cargo)
        id: cache-restore-cargo
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: x86_64-unknown-linux-gnu-x86_64-unknown-linux-gnu--cargo-${{ hashFiles('**/Cargo.toml') }}
      - name: Build with test codegen
        id: build-test-codegen
        run: cargo build -p rsonpath-test -vv
      - name: Upload generated tests as artifact
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: rsonpath-test-documents
          path: crates/rsonpath-lib/tests/documents
          retention-days: 1
